const DASH={summary:{products:[]},findings:[],history:{},attack_paths:{},quarantine:[],executive_brief:""};
const $=id=>document.getElementById(id);
const HAS_CHART=true;
const gridColor="rgba(255,255,255,.05)";
const cardCfg={};
(function initCharts(){if(!HAS_CHART)return;try{const S=DASH.summary,F=DASH.findings,H=DASH.history;
new Chart($('c-priority'),{type:'doughnut',data:{labels:['P1 Critical','P2 High','P3 Medium','P4 Low'],datasets:[{data:[S.p1,S.p2,S.p3,S.p4],backgroundColor:['#ef4444','#f97316','#eab308','#64748b'],borderWidth:0,hoverOffset:6,borderRadius:4}]},options:{...cardCfg,cutout:'68%',plugins:{legend:{display:true,position:'bottom',labels:{color:'#94a3b8',boxWidth:10,boxHeight:10,padding:12}},tooltip:{callbacks:{label:ctx=>`${ctx.label}: ${ctx.raw} findings`}}}}});
const sevCounts={critical:0,high:0,medium:0,low:0,info:0};F.forEach(f=>sevCounts[f.severity]=(sevCounts[f.severity]||0)+1);const sevLabels=['critical','high','medium','low','info'];
new Chart($('c-severity'),{type:'bar',data:{labels:sevLabels.map(s=>s.charAt(0).toUpperCase()+s.slice(1)),datasets:[{data:sevLabels.map(s=>sevCounts[s]||0),backgroundColor:['rgba(239,68,68,.8)','rgba(249,115,22,.8)','rgba(234,179,8,.8)','rgba(34,197,94,.8)','rgba(100,116,139,.8)'],borderWidth:0,borderRadius:4}]},options:{...cardCfg,indexAxis:'y',scales:{x:{grid:{color:gridColor},ticks:{color:'#94a3b8'}},y:{grid:{display:false},ticks:{color:'#94a3b8'}}},plugins:{legend:{display:false},tooltip:{callbacks:{label:ctx=>`${ctx.raw} findings`}}}}});
const scanMap={};F.forEach(f=>scanMap[f.scanner]=(scanMap[f.scanner]||0)+1);const scanKeys=Object.keys(scanMap).sort((a,b)=>scanMap[b]-scanMap[a]);
new Chart($('c-scanner'),{type:'bar',data:{labels:scanKeys,datasets:[{data:scanKeys.map(k=>scanMap[k]),backgroundColor:'rgba(6,182,212,.7)',borderWidth:0,borderRadius:4}]},options:{...cardCfg,indexAxis:'y',scales:{x:{grid:{color:gridColor},ticks:{color:'#94a3b8'}},y:{grid:{display:false},ticks:{color:'#94a3b8'}}},plugins:{legend:{display:false}}}});
new Chart($('c-noise'),{type:'bar',data:{labels:['Raw findings','After dedup','After filtering','Active'],datasets:[{label:'Findings',data:[S.raw_findings,S.unique_findings,S.unique_findings-S.quarantined,S.final_findings],backgroundColor:['rgba(59,130,246,.7)','rgba(6,182,212,.7)','rgba(234,179,8,.7)','rgba(34,197,94,.7)'],borderWidth:0,borderRadius:6}]},options:{...cardCfg,scales:{y:{grid:{color:gridColor},ticks:{color:'#94a3b8'}},x:{grid:{display:false},ticks:{color:'#94a3b8'}}},plugins:{legend:{display:false},tooltip:{callbacks:{label:ctx=>`${ctx.raw.toLocaleString()} findings`}}}}});
const colors=['#3b82f6','#06b6d4','#6366f1','#22c55e','#f97316'];const products=Object.keys(H);const histDatasets=[];products.forEach((prod,idx)=>{const runs=H[prod];if(!runs||runs.length<1)return;histDatasets.push({label:prod,data:runs.map(r=>({x:r.run_date,y:r.avg_score})),borderColor:colors[idx%colors.length],backgroundColor:'transparent',tension:.4,pointRadius:4,pointHoverRadius:6,borderWidth:2});});if(histDatasets.length){new Chart($('c-history'),{type:'line',data:{datasets:histDatasets},options:{...cardCfg,scales:{x:{type:'category',grid:{color:gridColor},ticks:{color:'#94a3b8',maxRotation:30}},y:{grid:{color:gridColor},ticks:{color:'#94a3b8'},title:{display:true,text:'Avg score',color:'#64748b'}}},plugins:{legend:{display:products.length>1,position:'bottom',labels:{color:'#94a3b8'}}}}});}else{$('c-history').parentElement.innerHTML='<p class="empty-state">Need 2+ pipeline runs to show trend.</p>';}
const epssData=F.filter(f=>f.epss_score>0&&f.score>0).map(f=>({x:parseFloat((f.epss_score*100).toFixed(2)),y:f.score,label:f.title,kev:f.kev,sev:f.severity}));
new Chart($('c-epss'),{type:'scatter',data:{datasets:[{label:'Findings',data:epssData,backgroundColor:epssData.map(p=>p.kev?'rgba(239,68,68,.75)':p.sev==='critical'?'rgba(239,68,68,.5)':p.sev==='high'?'rgba(249,115,22,.5)':p.sev==='medium'?'rgba(234,179,8,.5)':'rgba(34,197,94,.35)'),pointRadius:5,pointHoverRadius:8}]},options:{...cardCfg,scales:{x:{title:{display:true,text:'EPSS score (%)',color:'#64748b'},grid:{color:gridColor},ticks:{color:'#94a3b8'}},y:{title:{display:true,text:'Risk score',color:'#64748b'},grid:{color:gridColor},ticks:{color:'#94a3b8'},min:0,max:100}},plugins:{legend:{display:false},tooltip:{callbacks:{label:ctx=>{const d=ctx.raw;return[`${d.label.substring(0,40)}`,`EPSS: ${d.x}%  Score: ${d.y}`,d.kev?'⚠️ In CISA KEV':''];}}}}}});
const kevCount=F.filter(f=>f.kev).length;const exploitCount=F.filter(f=>f.exploit_available&&!f.kev).length;const epssHighCount=F.filter(f=>f.epss_score>.3&&!f.kev&&!f.exploit_available).length;const noIntelCount=F.length-kevCount-exploitCount-epssHighCount;
new Chart($('c-threat'),{type:'doughnut',data:{labels:['CISA KEV (confirmed exploit)','Exploit-DB match','EPSS > 30%','No active intel'],datasets:[{data:[kevCount,exploitCount,epssHighCount,noIntelCount],backgroundColor:['rgba(239,68,68,.85)','rgba(249,115,22,.8)','rgba(234,179,8,.7)','rgba(100,116,139,.4)'],borderWidth:0,hoverOffset:6,borderRadius:4}]},options:{...cardCfg,cutout:'60%',plugins:{legend:{display:true,position:'bottom',labels:{color:'#94a3b8',boxWidth:10,boxHeight:10,padding:10}}}}});}catch(e){console.error('initCharts:',e);}})();
