.PHONY: help install test deploy scan pipeline dashboard clean all

help:
	@echo "DevSecOps Risk Intelligence Pipeline"
	@echo ""
	@echo "Targets:"
	@echo "  make all              Full pipeline: deploy + scan + process + dashboard"
	@echo "  make deploy-targets  Start NodeGoat, Juice Shop, bWAPP"
	@echo "  make run-scanners     Run all 4 scanners against targets"
	@echo "  make run-pipeline     Process findings through 9 stages"
	@echo "  make dashboard        Generate HTML dashboard"
	@echo "  make test             Run unit tests"
	@echo "  make clean            Remove outputs and caches"
	@echo ""

install:
	pip install -r requirements.txt

deploy-targets:
	docker compose -f targets/docker-compose.yml up -d
	@echo "⏳ Waiting 30s for targets to start..."
	sleep 30

run-scanners: deploy-targets
	mkdir -p scan_reports
	# Resolve the NodeGoat image from the running container (compose builds
	# it locally, so the name is <project>-nodegoat — never assume webgoat).
	$(eval NODEGOAT_IMAGE := $(shell docker inspect --format='{{.Config.Image}}' nodegoat 2>/dev/null || echo targets-nodegoat))
	# Nuclei (resource-limited to prevent system crashes)
	docker run --rm --network=host --memory=1g --cpus=1 \
		-v $(PWD)/scan_reports:/out \
		projectdiscovery/nuclei:latest \
		-u http://localhost:4000 -jsonl -o /out/nodegoat_nuclei.json || true
	docker run --rm --network=host --memory=1g --cpus=1 \
		-v $(PWD)/scan_reports:/out \
		projectdiscovery/nuclei:latest \
		-u http://localhost:3000 -jsonl -o /out/juiceshop_nuclei.json || true
	docker run --rm --network=host --memory=1g --cpus=1 \
		-v $(PWD)/scan_reports:/out \
		projectdiscovery/nuclei:latest \
		-u http://localhost:8080 -jsonl -o /out/bwapp_nuclei.json || true
	# ZAP (baseline mode, capped at 1GB RAM)
	docker run --rm --network=host --memory=1g --cpus=1 \
		-v $(PWD)/scan_reports:/zap/wrk \
		ghcr.io/zaproxy/zaproxy:2.15.0 \
		zap-baseline.py -t http://localhost:4000 -J /zap/wrk/nodegoat_zap.json || true
	docker run --rm --network=host --memory=1g --cpus=1 \
		-v $(PWD)/scan_reports:/zap/wrk \
		ghcr.io/zaproxy/zaproxy:2.15.0 \
		zap-baseline.py -t http://localhost:3000 -J /zap/wrk/juiceshop_zap.json || true
	docker run --rm --network=host --memory=1g --cpus=1 \
		-v $(PWD)/scan_reports:/zap/wrk \
		ghcr.io/zaproxy/zaproxy:2.15.0 \
		zap-baseline.py -t http://localhost:8080 -J /zap/wrk/bwapp_zap.json || true
	# Trivy (scan container images with resource limits)
	docker run --rm --memory=512m --cpus=0.5 \
		-v $(PWD)/scan_reports:/out \
		aquasec/trivy:latest \
		image --format json -o /out/nodegoat_trivy.json $(NODEGOAT_IMAGE) || true
	docker run --rm --memory=512m --cpus=0.5 \
		-v $(PWD)/scan_reports:/out \
		aquasec/trivy:latest \
		image --format json -o /out/juiceshop_trivy.json bkimminich/juice-shop:v15.3.0 || true
	docker run --rm --memory=512m --cpus=0.5 \
		-v $(PWD)/scan_reports:/out \
		aquasec/trivy:latest \
		image --format json -o /out/bwapp_trivy.json raesene/bwapp:latest || true

run-pipeline:
	mkdir -p outputs
	python -m pipeline.run \
		--reports scan_reports/ \
		--config config.json \
		--out outputs/

dashboard: run-pipeline
	@echo "Dashboard already generated by run-pipeline: outputs/risk_dashboard.html"

all: deploy-targets run-scanners run-pipeline
	@echo "✅ Full pipeline complete!"

test:
	python -m pytest pipeline/tests/ -v --tb=short

test-coverage:
	python -m pytest pipeline/tests/ --cov=pipeline --cov-report=html

clean:
	rm -rf outputs/ scan_reports/ intel/ .threat_cache/
	find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
	docker compose -f targets/docker-compose.yml down 2>/dev/null || true
